# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=35, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Email')),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Пароль')),
            ],
        ),
    ]
