# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payday', '0005_auto_20170626_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
