# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payday', '0005_auto_20170626_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
