# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payday', '0006_entry_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='create_date',
        ),
    ]
