# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payday', '0008_entry_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='create_date',
            field=models.TimeField(verbose_name=datetime.datetime(2017, 7, 6, 16, 14, 2, 851774)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user_name',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
