# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('payday', '0009_auto_20170706_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='create_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.DateField(),
        ),
    ]
